language: go
dist: xenial

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - master

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/dep
    - webroot/node_modules

before_install:
  - nvm install 10.15.0
  - nvm use 10.15.0
  - npm install -g yarn

install:
  - make deps-install
  - cd webroot && make yarn-install && cd ..

script:
  - make check-style
  - make test
  - make build
  - cd webroot
  - make lint
  - make build
  - cd ..

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
    go: "1.11.x"
