version: "2"

services:

  db:
    image: mysql:5.7.17
    container_name: smsender_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=smsender
      - MYSQL_USER=smsender_user
      - MYSQL_PASSWORD=smsender_password

  app:
    depends_on:
      - db
    build: .
    image: smsender/smsender-preview
    container_name: smsender_app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./volumes/app/config:/smsender/config:rw
    environment:
      - MYSQL_DATABASE=smsender
      - MYSQL_USER=smsender_user
      - MYSQL_PASSWORD=smsender_password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306